### ISSUE TITLE
Use of VKPP_CALL() does not match definition in vkpp master

### ISSUE THREAD

**Issue by dov** [nyorain/vpp#11]
In vkpp master, VKPP_CALL() takes three parameters, but in the usage in vpp, only one parameter is given. Compilation therefore fails.

**Comment by nyorain** [comment]
I just merged the right branch into master here, it compiles for me now. Please post the compiler output if it still doesn't work for you.
Thank you for making me fix builds on master for all my repos btw, appreciated :D

**Comment by dov** [comment]
My pleasure, or perhaps masochism. :-)

vpp now compiles cleanly on my side including intro_glfw. 

intro_ny also compiles though with a single warning:

```
Dependency ny from subproject subprojects/ny found: YES
Dependency glfw3 found: YES (cached)
Build targets in project: 6
Found ninja-1.9.0 at /usr/bin/ninja
[36/37] Compiling C++ object 'docs/exa...50135fc@@intro_ny@exe/intro_ny.cpp.o'.
In file included from ../docs/examples/intro_ny.cpp:32:
../subprojects/ny/include/ny/keyboardContext.hpp:15:7: warning: ‘class ny::KeyboardContext’ has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
   15 | class KeyboardContext {
      |       ^~~~~~~~~~~~~~~
[37/37] Linking target docs/examples/intro_ny.
```

Great! No on to rvg....Which still fails on the vkpp output.cpp bug. I guess you haven't refreshed it yet.

**Comment by nyorain** [comment]
Good to hear!
